### ISSUE TITLE
Huge memory usage for Ubuntu Server 18.04

### ISSUE THREAD

**Issue by Nathan1258** [ihabunek/twitch-dl#115] opened 2022-11-11 00:00 UTC
I have an array full of twitch links, as I loop and download them, more and more of my memory is getting consumed until finally the OS kills it once I run out with SIGKIL.

I've seen this problem as an issue before, however no solution was provided and it was for Windows - WSL.

This is on the latest release of twitch-dl

**Comment by ihabunek** [comment] 2024-09-10 07:24
Since version 2.9.0 VODs will be downloaded to the cache folder, not temp, so this should be fixed. Please test.
(duplicate of #105)

**Closed by ihabunek** 2024-09-10 07:24 UTC
