### ISSUE TITLE
Restricted vods

### ISSUE THREAD

**Issue by tomg55555** [ihabunek/twitch-dl#100] opened 2022-06-13 14:33 UTC
Hello, I'm editor of a channel that decided to made vod sub only. I'm aware of different methods to download them avoid the direct download from twitch but I love your tool and the possibility to decides which parts of the vod you can download and once seen is not yet implemented or not programmed in the near future I would like to give a suggest or inspiration in order to facilitate the implementation of it.
As reference, even if I think you already know this solution I would suggest to have a look at "twitch recover" (https://github.com/TwitchRecover/TwitchRecover). With this tool you're able to get vods even if they're sub only.
Another option might be pass an autentication key while downloading the vod.
I havent looked at your code yet and I don't think I would be personally able to implement it (I'll try) but Ihope this suggestion could be useful cause this is the best tool out there. Apreciate your your work, thank you.

**Comment by ihabunek** [comment] 2022-06-25 07:48
Thanks for getting in touch. We have a solution for this, will be in the next release. Closing this ticket as duplicate of #48.

**Closed by ihabunek** 2022-06-25 07:48 UTC
