### ISSUE TITLE
Download Vods restricted to sub only

### ISSUE THREAD

**Issue by tomg55555** [ihabunek/twitch-dl#99] opened 2022-06-07 17:12 UTC
Hello, I'm an editor of the channel which streams 12h straight and I need to download just 2-3 hours but recently the streamer activated the restrictions to subs only, as a sub is there any way to authenticate to download the video?

**Comment by ihabunek** [comment] 2022-06-09 08:52
Sorry, this is not currently supported. It's probably possible but would be janky to implement.

Duplicate of https://github.com/ihabunek/twitch-dl/issues/48.

**Closed by ihabunek** 2022-06-09 08:52 UTC
